"""Adicionando created_at e updated_at na tabela de todos

Revision ID: babc62e28b3e
Revises: eca43333b6ea
Create Date: 2026-07-24 10:06:30.578002

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "babc62e28b3e"
down_revision: Union[str, Sequence[str], None] = "eca43333b6ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("todos", sa.Column("user_id", sa.Integer(), nullable=False))
    op.add_column(
        "todos",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
    )
    op.add_column(
        "todos",
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
    )
    op.create_foreign_key(None, "todos", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "todos", type_="foreignkey")
    op.drop_column("todos", "updated_at")
    op.drop_column("todos", "created_at")
    op.drop_column("todos", "user_id")
    # ### end Alembic commands ###
